# mkdocs.yml - https://realpython.com/python-project-documentation-with-mkdocs
site_name: Template for Telegram Bots - Documentation
theme:
  name: material
  features:
    - content.code.annotate
  palette:
    primary: teal
    accent: light green
  font:
    text: Exo 2
    code: Hack
  language: es
  favicon: assets/icon.png
  logo: assets/icon.png

plugins: 
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            heading_level: 2

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: 
        true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: true
      toc_depth: 8
      baselevel: 2
  - tables

nav:
  - Home: index.md
  - Code:
    - Main file: my_telegram_bot.md
    - Command Handlers: command_handlers.md
    - Message Handlers: message_handlers.md
    - Utils: utils.md

extra: 
  generator: false